### ISSUE TITLE
Clinical Trial search en.irct.ir link does not work

### ISSUE THREAD

**Issue by redtruck99** [brunoamaral/gregory#375]
On the Clinical Trial page I searched:
Title: probiotic
Recruiting status: Recruiting
Results: 10 trials
Links to anzctr and clinicaltrials work, but en.irct.ir does not work.

**Comment by brunoamaral** [comment]
@redtruck99 thank you for logging the issue. 

I've sent an email to the WHO Registry explaining the problem and pointing to this thread.

There isn't much we can do from our side other than flag broken links or let people know beforehand that it may happen.

Let's keep this issue open for a while until they respond.

**Comment by brunoamaral** [comment]
I'm closing this because we never heard back from the ICTRP. Here's the email I had sent them on the 28th of February.

From: Bruno Amaral
Email: bruno@gregory-ms.com

Subject: Registry Network

Comments: "Hello, at the website https://gregory-ms.com/ we have been listing your clinical trials using the data from the exported XML file. Some of our users have found broken links in your database and logged an issue on GitHub: https://github.com/brunoamaral/gregory/issues/375 We understand that this may be something out of our reach, but if there is anything we can do to help, please let us know. Kind regards, Bruno Amaral"
